TOKENIZERS_PARALLELISM=false python main.py --gpus 1 \
	--accelerator ddp \
	--max_epochs 10 \
	--lr 1e-5 \
	--train_batchsize 16 \
	--valid_batchsize 16 \
	--num_workers 8 \
	--val_check_interval 0.5 \
	--pretrain_model mrm8488/distill-bert-base-spanish-wwm-cased-finetuned-spa-squad2-es \
	--model_name BertLSTMModel \
	--rnn_size 256 \
	--rnn_nlayer 1 \
	--use_crf \
	--data_dir ./data/spanish \
	--save_dir ./save/spanish
