CUDA_VISIBLE_DEVICES=7 TOKENIZERS_PARALLELISM=false python main.py --gpus 1 \
	--accelerator ddp \
	--max_epochs 10 \
	--lr 1e-5 \
	--train_batchsize 16 \
	--valid_batchsize 16 \
	--num_workers 8 \
	--val_check_interval 0.5 \
	--pretrain_model camembert-base \
	--model_name BertLSTMModel \
	--rnn_size 256 \
	--rnn_nlayer 1 \
	--use_crf \
	--data_dir ./data/french \
	--save_dir ./save/french
